spring.application.name=Todo
server.port=8080
# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# Postman url
# Login = POST http://localhost:8080/auth/login
# Register = POST http://localhost:8080/auth/register






#To-do url
# Particular id = GET http://localhost:8080/api/v1/todo/{id}
# Get all =GET http://localhost:8080/api/v1/todo
# Create =POST http://localhost:8080/api/v1/todo/create


